// src/shared/constants/itemImageMap.ts

/**
 * Маппинг ID предметов на пути к изображениям
 * Используется для получения пути к изображению предмета по его ID
 */
export const itemImageMap: Record<string, string> = {
    "1": "gauntlets_of_strength.jpg",
    "2": "belt_of_strength.jpg",
    "3": "bracer.jpg",
    "4": "vitality_booster.jpg",
    "5": "ogre_axe.jpg",
    "6": "reaver.jpg",
    "7": "heart_of_tarrasque.jpg",
    "8": "tango.jpg",
    "9": "ring_of_regen.jpg",
    "10": "ring_of_health.jpg",
    "11": "tranquil_boots.jpg",
    "12": "ring_of_tarrasque.jpg",
    "13": "mantle_of_intelligence.jpg",
    "14": "robe_of_the_magi.jpg",
    "15": "null_talisman.jpg",
    "16": "energy_booster.jpg",
    "17": "staff_of_wizardry.jpg",
    "18": "mystic_staff.jpg",
    "19": "parasma.jpg",
    "20": "clarity.jpg",
    "21": "sages_mask.jpg",
    "22": "void_stone.jpg",
    "23": "soul_ring.jpg",
    "24": "arcane_boots.jpg",
    "25": "tiara_of_selemene.jpg",
    "26": "blades_of_attack.jpg",
    "27": "broadsword.jpg",
    "28": "claymore.jpg",
    "29": "mithril_hammer.jpg",
    "30": "crystalys.jpg",
    "31": "desolator.jpg",
    "32": "daedalus.jpg",
    "33": "divine_rapier.jpg",
    "34": "morbid_mask.jpg",
    "35": "mask_of_madness.jpg",
    "36": "vladmirs_offering.jpg",
    "37": "satanic.jpg",
    "38": "wind_lace.jpg",
    "39": "boots_of_speed.jpg",
    "40": "phase_boots.jpg",
    "41": "boots_of_travel.jpg",
    "42": "boots_of_travel_2.jpg",
    "43": "quelling_blade.jpg",
    "44": "hand_of_midas.jpg",
    "45": "battle_fury.jpg",
    "46": "radiance.jpg"
  };